---
title       : Sintaxis
description : Después de realizar los ejercicios de esta sección deberíamos\:
• Conocer las diferentes construcciones que ofrece R para escribir expresiones.
• Escribir expresiones válidas.
• Comprender que son los objetos.
• Ser capaz de examinar el tipo y clase de un objeto.
• Conocer los diferentes tipos de datos básicos en R.
• Entender el concepto de coerción.
• Comprender la importancia de adoptar un buen estilo para nuestro código.
attachments :
  slides_link : https://s3.amazonaws.com/assets.datacamp.com/course/teach/slides_example.pdf

---

---
## Expresiones y asignación

```yaml
type: NormalExercise
lang: r
xp: 100
skills: 1
```


`@instructions`

`@hint`

`@pre_exercise_code`
```{r}

```

`@sample_code`
```{r}

```

`@solution`
```{r}

```

`@sct`
```{r}
test
```

---
## Objetos

```yaml
type: MultipleChoiceExercise
lang: r
xp: 50
skills: 1
```


`@instructions`

`@hint`

`@pre_exercise_code`
```{r}

```

`@sct`
```{r}

```

---
## Datos Básicos en R

```yaml
type: PlainMultipleChoiceExercise
lang: r
xp: 50
skills: 1
```


`@instructions`

`@hint`

`@pre_exercise_code`
```{r}

```

`@sct`
```{r}

```










